manipalutsav/frontend

src/services/college.js, src/services/colleges.js, src/services/events.js, src/services/judges.js, src/services/leaderboard.js, src/services/users.js, src/utils/request.js
This will change how services work, in the future.
=> New services!

src/services/collegeServices.js, src/services/eventService.js, src/services/judgeServices.js, src/services/leaderboardServices.js, src/services/userServices.js, src/utils/request.js
~~TODO: replace all fetch calls to with the `request` wrapper in `./src/utils/request.js` so that every request sets the `Authorization` header.~~
This is a breaking change, so please test all modules (each and every actions in the UI) before approving/merging it, otherwise it'll break everything.
=> Use Authorization header in request wrapper

src/components/Volunteer/CoreVolunteer.jsx
* Capitalized shirt size acronyms
* Change shirt size label from X Large to Extra Large
=> Shirt size label updates

package.json, src/components/Events/ParticipationStatus.jsx, src/components/Events/index.jsx, src/components/Profile/index.jsx
Sambit requested for the Logout button to be reworked to use an alert instead of the current "Sure?" option, this PR implements that
=> Logout reworked and bug fixes

src/components/Volunteer/Volunteer.jsx, src/components/Volunteer/VolunteerEdit.jsx, src/components/Volunteer/index.jsx, src/pages/index.jsx, src/services/volunteerService.js, src/utils/common.js
> **Note**
> Before merge, ensure https://github.com/manipalutsav/backend/pull/35 is merged to testing.
=> Added feature to enter other volunteers

src/components/Index/index.jsx
=> Feature update timer

src/components/Rounds/AddEdit.jsx, src/components/Rounds/Leaderboard.jsx, src/utils/common.js
=> Fixed rounds edit screen

package-lock.json, package.json, src/commons/Sidebar/index.jsx
Committed on behalf of @anushravishankar
=> Sidebar decluttering done by @anushravishankar

src/commons/Block/index.jsx, src/components/Events/index.jsx, src/components/Events/style.css, src/components/Judges/index.jsx, src/components/Judges/style.css, src/components/Registration/index.jsx, src/components/Registration/style.css
Added searchbar and fixed the table data overlapping bug in events page.
=> Add Search bar for Judges, Events, Registration page FIX #278 #279 #280

src/components/Colleges/index.jsx, src/components/Registration/index.jsx, src/components/Users/index.jsx
- Fixed vertical height of cards in Registration page.
- Changed the color of the event status indicator pill in Registration Page.
- All cards responsive.
=> Minor UI Changes

src/components/Colleges/index.jsx, src/components/Events/Add.jsx, src/components/Events/index.jsx, src/components/Events/style.css, src/components/Judges/index.jsx, src/components/Users/index.jsx, src/components/Volunteer/CoreVolunteer copy.jsx, src/components/Volunteer/index.jsx, src/layouts/base.css
- Added color on hover on CTA
- Fixed form alignment of events add page
- fixed table overlap bug on volunteers page
=> Add hover colors on CTA, fix volunteers page table bug

src/commons/Sidebar/index.jsx, src/components/Colleges/index.jsx
=> Hid 'admin only' menu from other users

src/commons/Header/index.jsx, src/pages/board.jsx, src/pages/publicboard.jsx
- Updated the staff event name
- Fixed the profile button in header breaking in small screen
=> Updated staff desserts event in board

src/components/Registration/Participants.jsx, src/components/Registration/UpdateTeams.jsx, src/utils/common.js
The commit updates the isTeamChangeFreezed function to determine whether team changes are allowed based on a new edit window period. Instead of relying on hardcoded freeze dates, the function now dynamically checks if the current date falls between the registration start and end dates of the event. If it does, team changes are allowed (false is returned). Otherwise, changes remain frozen (true is returned). The previously commented-out hardcoded freeze logic has also been removed.
Additionally, the commit includes a feature to allow registration for the remaining participant count, though the details of that change are not visible in the provided function.
=> Added the feature to allow the registration for remaining participant count, and modified the isTeamChangeFreezed function

src/components/Registration/UpdateTeams.jsx
Issue:
- Previously, the validation for registration ID was not working correctly when adding new participants to a team. It did not check whether the new participants' IDs had already been used.
Fix:
- Fetched the existing participants of the team.
- Compared the new participants' IDs with the already registered ones.
- Ensured that duplicate registration IDs are not allowed when adding new participants.
Impact:
- This fix prevents duplicate participant registrations within a team, ensuring data integrity.
=> Fixed the bug where the registration id validation for second time wasnt working

src/components/Judges/index.jsx
Commented out judge delete button
=> Commented out judge delete button

src/components/Judges/index.jsx, src/components/Registration/UpdateTeams.jsx, src/components/Volunteer/Volunteer.jsx
This commit includes some fixes to delete the volunteers and also uncommented the judge deleteion button.
=> enabled the feature to delete the volunteer

src/commons/Header/index.jsx
enabled SLOTS and STATS on NavBar
=> enabled SLOTS and STATS on NavBar

src/commons/Header/index.jsx, src/components/PracticeSlots/index.jsx, src/components/PublicPracticeSlots/index.jsx
Unhinding public PracticeSlots from nav bar and PracticeSlots in admin dropdown
=> Unhinding public PracticeSlots from nav bar and PracticeSlots in admin dropdown

src/components/PracticeSlots/index.jsx
=> Unhiding reset slot button

src/commons/Header/index.jsx, src/commons/Sidebar/index.jsx
Unhide stats slots in side bar
and practice slots for admin in side bar
=> Unhide stats slots and practice slots in side bar

src/commons/Dialog/index.jsx, src/components/Judges/StartJudging.jsx
changed the feed back headder message
updated dialog component to hide cancel button
=> changed the feed back headder message

src/components/Events/index.jsx, src/components/Index/index.jsx
1. Removed the fetching of teams from each events to calculate noOfOu…tstation in table view , removed the noOfOutstation column from table as well,
2. commented the  fetchData() method call responsible for fetching teams for calculating noOfOutstation which was no longer in use
=> fixed bug where multiple api calls for teams were being sent

src/commons/Header/index.jsx, src/commons/Sidebar/index.jsx, src/components/Leaderboard/index.jsx, src/components/PublicLeaderboard/index.jsx, src/pages/index.jsx, src/pages/publicboard.jsx
Reverted the changes that made on public event standings.
Made the event standings route available with its nav links/sidebar links.
=> Reverted-event-standings

src/utils/common.js
fixed DOC name to 'Department of Commerce (MSCE)': 'DOC (MSCE)',
=> fixed DOC name to 'Department of Commerce (MSCE)': 'DOC (MSCE)',

src/components/Leaderboard/index.jsx, src/components/PublicLeaderboard/index.jsx, src/pages/publicboard.jsx
Fixed the score display mismatch in the public leaderboard and the public leaderboard chart.
Disabled the "Publish" button in the admin only leaderboard.
Made both public leaderboard and public leaderboard chart to request on newly created leaderboard api.
=> fixed-leaderboard-score-mismatch
